version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tpbt
      POSTGRES_PASSWORD: tpbt
      POSTGRES_DB: tpbt
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - pgdata
    ports:
        - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    pgdata: